In [2]:
import pandas as pd
import numpy as np
import gc

pd.set_option('display.max_columns', None)

-----
### 2024

In [2]:
df_2024 = pd.read_csv('datos_grd/GRD_PUBLICO_2024.txt', 
                      sep='|', 
                      encoding='Latin-1',
                      low_memory=False)

#parse_dates=['FECHA_NACIMIENTO', 'FECHA_INGRESO', 'FECHATRASLADO1', 'FECHATRASLADO2', 'FECHATRASLADO3', 'FECHATRASLADO4', 'FECHATRASLADO5', 'FECHATRASLADO6', 'FECHATRASLADO7', 'FECHATRASLADO8', 'FECHATRASLADO9', 'FECHAALTA', 'FECHAPROCEDIMIENTO1', 'FECHAINTERV1']

In [25]:
df_2024.head()

,COD_HOSPITAL,ID_BENEFICIARIO,SEXO,FECHA_NACIMIENTO,ETNIA,PROVINCIA,COMUNA,NACIONALIDAD,PREVISION,SERVICIO_SALUD,TIPO_PROCEDENCIA,TIPO_INGRESO,ESPECIALIDAD_MEDICA,TIPO_ACTIVIDAD,FECHA_INGRESO,SERVICIOINGRESO,FECHATRASLADO1,SERVICIOTRASLADO1,FECHATRASLADO2,SERVICIOTRASLADO2,FECHATRASLADO3,SERVICIOTRASLADO3,FECHATRASLADO4,SERVICIOTRASLADO4,FECHATRASLADO5,SERVICIOTRASLADO5,FECHATRASLADO6,SERVICIOTRASLADO6,FECHATRASLADO7,SERVICIOTRASLADO7,FECHATRASLADO8,SERVICIOTRASLADO8,FECHATRASLADO9,SERVICIOTRASLADO9,FECHAALTA,SERVICIOALTA,TIPOALTA,CONDICIONDEALTANEONATO1,PESORN1,SEXORN1,RN1ESTADO,CONDICIONDEALTANEONATO2,PESORN2,SEXORN2,RN2ESTADO,CONDICIONDEALTANEONATO3,PESORN3,SEXORN3,RN3ESTADO,CONDICIONDEALTANEONATO4,PESORN4,SEXORN4,RN4ESTADO,DIAGNOSTICO1,DIAGNOSTICO2,DIAGNOSTICO3,DIAGNOSTICO4,DIAGNOSTICO5,DIAGNOSTICO6,DIAGNOSTICO7,DIAGNOSTICO8,DIAGNOSTICO9,DIAGNOSTICO10,DIAGNOSTICO11,DIAGNOSTICO12,DIAGNOSTICO13,DIAGNOSTICO14,DIAGNOSTICO15,DIAGNOSTICO16,DIAGNOSTICO17,DIAGNOSTICO18,DIAGNOSTICO19,DIAGNOSTICO20,DIAGNOSTICO21,DIAGNOSTICO22,DIAGNOSTICO23,DIAGNOSTICO24,DIAGNOSTICO25,DIAGNOSTICO26,DIAGNOSTICO27,DIAGNOSTICO28,DIAGNOSTICO29,DIAGNOSTICO30,DIAGNOSTICO31,DIAGNOSTICO32,DIAGNOSTICO33,DIAGNOSTICO34,DIAGNOSTICO35,PROCEDIMIENTO1,PROCEDIMIENTO2,PROCEDIMIENTO3,PROCEDIMIENTO4,PROCEDIMIENTO5,PROCEDIMIENTO6,PROCEDIMIENTO7,PROCEDIMIENTO8,PROCEDIMIENTO9,PROCEDIMIENTO10,PROCEDIMIENTO11,PROCEDIMIENTO12,PROCEDIMIENTO13,PROCEDIMIENTO14,PROCEDIMIENTO15,PROCEDIMIENTO16,PROCEDIMIENTO17,PROCEDIMIENTO18,PROCEDIMIENTO19,PROCEDIMIENTO20,PROCEDIMIENTO21,PROCEDIMIENTO22,PROCEDIMIENTO23,PROCEDIMIENTO24,PROCEDIMIENTO25,PROCEDIMIENTO26,PROCEDIMIENTO27,PROCEDIMIENTO28,PROCEDIMIENTO29,PROCEDIMIENTO30,MEDICOINTERV1_ENCRIPTADO,FECHAPROCEDIMIENTO1,FECHAINTERV1,ESPECIALIDADINTERVENCION,MEDICOALTA_ENCRIPTADO,USOSPABELLON,IR_29301_COD_GRD,IR_29301_PESO,IR_29301_SEVERIDAD,IR_29301_MORTALIDAD,HOSPPROCEDENCIA
0,107102,77447810,MUJER,1939-09-18,NINGUNO,MARGA MARGA,VILLA ALEMANA,CHILE,FONASA INSTITUCIONAL - (MAI) B,VIÑA DEL MAR QUILLOTA,"CENTRO ESPECIALIDADES (CDT, CRS, CONSULTORIO A...",PROGRAMADA,OFTALMOLOGÍA,CIRUGÍA MAYOR AMBULATORIA (CMA),2024-03-23,UNIDAD DE RECUPERACIÓN DE PABELLONES (CENTRAL ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-03-23,UNIDAD DE RECUPERACIÓN DE PABELLONES (CENTRAL ...,DOMICILIO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,H26.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.41,13.71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71043147.0,NaN,2024-03-23,OFTALMOLOGÍA,71043147,1.0,022360,"0,4384",0,0,NaN
1,107100,81269680,MUJER,1952-05-31,NINGUNO,VALPARAISO,VIÑA DEL MAR,CHILE,FONASA INSTITUCIONAL - (MAI) D,VIÑA DEL MAR QUILLOTA,SERVICIO EMERGENCIA (DOMICILIO),URGENCIA,HEMATOLOGÍA,HOSPITALIZACIÓN,2024-09-26,UNIDAD DE CUIDADOS INTENSIVOS ADULTO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-10-02,UNIDAD DE CUIDADOS INTENSIVOS ADULTO,FALLECIDO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,M31.1,R57.2,A41.5,A41.0,R41.8,R56.8,J96.09,N17.9,R41.0,D64.9,R16.1,N28.1,J90,E80.6,D70,D47.3,Z92.4,Z86.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96.72,96.04,99.23,99.07,99.28,99.21,88.01,87.03,89.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78588090,NaN,041023,"5,8207",3,3,NaN
2,105101,77590791,HOMBRE,2012-07-17,NINGUNO,ELQUI,LA SERENA,CHILE,FONASA INSTITUCIONAL - (MAI) A,COQUIMBO,SERVICIO EMERGENCIA (DOMICILIO),URGENCIA,PEDIATRÍA,HOSPITALIZACIÓN,2024-01-22,PEDIATRÍA,2024-01-22,PEDIATRÍA,2024-01-22,PEDIATRÍA,2024-01-22,PEDIATRÍA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-01-26,PEDIATRÍA,DOMICILIO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,K12.2,K02.9,E66.8,K01.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0,23.19,99.21,99.29,99.23,99.26,93.96,87.11,89.31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71831896.0,NaN,2024-01-26,"CIRUGÍA DE CABEZA, CUELLO Y MAXILOFACIAL",75735052,2.0,034141,"0,4462",1,1,HOSPITAL SAN PABLO (COQUIMBO)
3,112100,77589537,HOMBRE,1952-11-03,NINGUNO,SANTIAGO,ÑUÑOA,CHILE,FONASA INSTITUCIONAL - (MAI) D,METROPOLITANO ORIENTE,"CENTRO ESPECIALIDADES (CDT, CRS, CONSULTORIO A...",PROGRAMADA,UROLOGÍA,HOSPITALIZACIÓN,2024-04-08,AREA MEDICO-QUIRURGICO CUIDADOS MEDIOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-04-14,AREA MEDICO-QUIRURGICO CUIDADOS MEDIOS,DOMICILIO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C61,K63.1,K66.0,E66.9,Z53.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.33,54.59,45.91,99.21,99.29,93.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80215470.0,NaN,2024-04-08,UROLOGÍA,83828813,1.0,061203,"3,5647",3,3,NaN
4,118100,94523630,MUJER,1994-02-28,NINGUNO,CONCEPCION,SAN PEDRO DE LA PAZ,PERÚ,FONASA INSTITUCIONAL - (MAI) C,CONCEPCIÓN,"APS URGENCIA (SAPU, SUR, SUC)",URGENCIA,CIRUGÍA GENERAL,HOSPITALIZACIÓN,2024-09-24,CIRUGÍA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-09-26,CIRUGÍA,DOMICILIO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,K35.8,K42.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.01,89.04,88.76,99.29,99.21,99.19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98438434.0,NaN,2024-09-24,CIRUGÍA GENERAL,98438434,1.0,061131,"0,7398",1,1,NaN

In [4]:
parse_dates = ['FECHA_NACIMIENTO', 'FECHA_INGRESO', 'FECHATRASLADO1', 'FECHATRASLADO2', 'FECHATRASLADO3', 'FECHATRASLADO4', 'FECHATRASLADO5', 'FECHATRASLADO6', 'FECHATRASLADO7', 'FECHATRASLADO8', 'FECHATRASLADO9', 'FECHAALTA', 'FECHAPROCEDIMIENTO1', 'FECHAINTERV1']

for col in parse_dates:
    df_2024[col] = pd.to_datetime(df_2024[col], format='%Y-%m-%d', errors='coerce')

df_2024['FECHA_NACIMIENTO'].dropna(inplace=True)
df_2024['FECHA_INGRESO'].dropna(inplace=True)

In [6]:
limpiar_cols = ['SEXO', 'COMUNA', 'TIPO_INGRESO', 'PREVISION']

for col in limpiar_cols:
    df_2024 = df_2024[df_2024[col] != 'DESCONOCIDO']

In [7]:
df_2024['SEXO'].value_counts()

SEXO
MUJER     632583
HOMBRE    453025
Name: count, dtype: int64

In [8]:
df_2024['COMUNA'].value_counts()

COMUNA
PUENTE ALTO      39491
LA FLORIDA       21818
MAIPU            21490
VALPARAISO       20695
ARICA            20352
                 ...
CAMARONES            9
LAGUNA BLANCA        7
ANTÁRTICA            5
PUTRE                4
GENERAL LAGOS        4
Name: count, Length: 343, dtype: int64

In [9]:
df_2024['TIPO_INGRESO'].value_counts()

TIPO_INGRESO
URGENCIA      552000
PROGRAMADA    388681
OBSTETRICA    144927
Name: count, dtype: int64

In [10]:
df_2024['PREVISION'].value_counts()

PREVISION
FONASA INSTITUCIONAL - (MAI) B    529130
FONASA INSTITUCIONAL - (MAI) A    225852
FONASA INSTITUCIONAL - (MAI) D    159595
FONASA INSTITUCIONAL - (MAI) C    139096
FONASA LIBRE ELECCIÓN (FMLE_B)      9728
FONASA LIBRE ELECCIÓN (FMLE_D)      5968
ISAPRE                              5815
PARTICULAR                          3530
FONASA LIBRE ELECCIÓN (FMLE_C)      2963
DIPRECA                             2595
CAPREDENA                            826
CAJA DE PREVISIÓN FFAA (SISA)        510
Name: count, dtype: int64

In [26]:
df_2024['ETNIA'].value_counts()

ETNIA
NINGUNO                    1058981
MAPUCHE                      20494
AYMARA                        2637
RAPA NUI (PASCUENSE)          1339
DIAGUITA                      1106
QUECHUA                        403
YAGÁN (YÁMANA)                 276
KAWÉSQAR                       250
COLLA                          169
LICAN ANTAI (ATACAMEÑO)        158
Name: count, dtype: int64

In [11]:
df_2024.to_csv('datos_unidos.csv', index=False, encoding='utf-8-sig')

In [12]:
del df_2024
gc.collect()

261

-------

### 2023

In [ ]:
df_2023 = pd.read_csv('datos_grd/GRD_PUBLICO_2023.txt', 
                      sep='|',
                      encoding='UTF-16',
                      low_memory=False)

In [21]:
df_2023.head()

,COD_HOSPITAL,CIP_ENCRIPTADO,SEXO,FECHA_NACIMIENTO,ETNIA,PROVINCIA,COMUNA,NACIONALIDAD,PREVISION,SERVICIO_SALUD,TIPO_PROCEDENCIA,TIPO_INGRESO,ESPECIALIDAD_MEDICA,TIPO_ACTIVIDAD,FECHA_INGRESO,SERVICIOINGRESO,FECHATRASLADO1,SERVICIOTRASLADO1,FECHATRASLADO2,SERVICIOTRASLADO2,FECHATRASLADO3,SERVICIOTRASLADO3,FECHATRASLADO4,SERVICIOTRASLADO4,FECHATRASLADO5,SERVICIOTRASLADO5,FECHATRASLADO6,SERVICIOTRASLADO6,FECHATRASLADO7,SERVICIOTRASLADO7,FECHATRASLADO8,SERVICIOTRASLADO8,FECHATRASLADO9,SERVICIOTRASLADO9,FECHAALTA,SERVICIOALTA,TIPOALTA,CONDICIONDEALTANEONATO1,PESORN1,SEXORN1,RN1ESTADO,CONDICIONDEALTANEONATO2,PESORN2,SEXORN2,RN2ESTADO,CONDICIONDEALTANEONATO3,PESORN3,SEXORN3,RN3ESTADO,CONDICIONDEALTANEONATO4,PESORN4,SEXORN4,RN4ESTADO,DIAGNOSTICO1,DIAGNOSTICO2,DIAGNOSTICO3,DIAGNOSTICO4,DIAGNOSTICO5,DIAGNOSTICO6,DIAGNOSTICO7,DIAGNOSTICO8,DIAGNOSTICO9,DIAGNOSTICO10,DIAGNOSTICO11,DIAGNOSTICO12,DIAGNOSTICO13,DIAGNOSTICO14,DIAGNOSTICO15,DIAGNOSTICO16,DIAGNOSTICO17,DIAGNOSTICO18,DIAGNOSTICO19,DIAGNOSTICO20,DIAGNOSTICO21,DIAGNOSTICO22,DIAGNOSTICO23,DIAGNOSTICO24,DIAGNOSTICO25,DIAGNOSTICO26,DIAGNOSTICO27,DIAGNOSTICO28,DIAGNOSTICO29,DIAGNOSTICO30,DIAGNOSTICO31,DIAGNOSTICO32,DIAGNOSTICO33,DIAGNOSTICO34,DIAGNOSTICO35,PROCEDIMIENTO1,PROCEDIMIENTO2,PROCEDIMIENTO3,PROCEDIMIENTO4,PROCEDIMIENTO5,PROCEDIMIENTO6,PROCEDIMIENTO7,PROCEDIMIENTO8,PROCEDIMIENTO9,PROCEDIMIENTO10,PROCEDIMIENTO11,PROCEDIMIENTO12,PROCEDIMIENTO13,PROCEDIMIENTO14,PROCEDIMIENTO15,PROCEDIMIENTO16,PROCEDIMIENTO17,PROCEDIMIENTO18,PROCEDIMIENTO19,PROCEDIMIENTO20,PROCEDIMIENTO21,PROCEDIMIENTO22,PROCEDIMIENTO23,PROCEDIMIENTO24,PROCEDIMIENTO25,PROCEDIMIENTO26,PROCEDIMIENTO27,PROCEDIMIENTO28,PROCEDIMIENTO29,PROCEDIMIENTO30,MEDICOINTERV1_ENCRIPTADO,FECHAPROCEDIMIENTO1,FECHAINTERV1,ESPECIALIDADINTERVENCION,MEDICOALTA_ENCRIPTADO,USOSPABELLON,IR_29301_COD_GRD,IR_29301_PESO,IR_29301_SEVERIDAD,IR_29301_MORTALIDAD,HOSPPROCEDENCIA
0,122100,72196813,HOMBRE,1980-04-13,OTRO,VALDIVIA,PANGUIPULLI,CHILE,FONASA INSTITUCIONAL - (MAI) A,VALDIVIA,SERVICIO EMERGENCIA (DOMICILIO),URGENCIA,CIRUGÍA GENERAL,HOSPITALIZACIÓN,2023-03-12,TRAUMATOLOGÍA Y ORTOPEDIA,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,2023-03-14,TRAUMATOLOGÍA Y ORTOPEDIA,DOMICILIO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,K35.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.03,93.11,93.18,96.59,90.59,90.39,99.29,99.21,99.18,47.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,87553213,NaN,064161,"0,7094",1,1,NaN
1,114101,DESCONOCIDO,HOMBRE,2001-11-04,OTRO,CORDILLERA,PUENTE ALTO,VENEZUELA (REPÚBLICA BOLIVARIANA DE),PARTICULAR,METROPOLITANO SURORIENTE,SERVICIO EMERGENCIA (DOMICILIO),URGENCIA,CIRUGÍA GENERAL,HOSPITALIZACIÓN,2023-11-04,DERIVACIÓN MÉDICO QUIRÚRGICO,2023-11-06,CIRUGÍA,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,2023-11-10,CIRUGÍA,DOMICILIO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J93.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.20,34.09,87.41,87.44,93.96,93.18,99.19,99.21,99.26,99.29,89.65,90.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,86895434,1.0,041301,"1,0869",1,1,NaN
2,114101,97627974,HOMBRE,2020-07-30,OTRO,CORDILLERA,PUENTE ALTO,CHILE,FONASA INSTITUCIONAL - (MAI) A,METROPOLITANO SURORIENTE,"APS URGENCIA (SAPU, SUR, SUC)",URGENCIA,PEDIATRÍA,HOSPITALIZACIÓN,2023-06-07,PEDIATRÍA,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,2023-06-08,PEDIATRÍA,HOSPITALIZACIÓN DOMICILIARIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J12.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,93.96,87.44,99.29,90.59,90.39,93.18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,73227424,NaN,044161,"0,4084",1,1,NaN
3,106103,67770674,MUJER,1978-11-14,OTRO,SAN ANTONIO,SAN ANTONIO,CHILE,FONASA INSTITUCIONAL - (MAI) C,VALPARAISO SAN ANTONIO,PLAN DE RESOLUCIÓN LE,PROGRAMADA,OBSTETRICIA Y GINECOLOGÍA,HOSPITALIZACIÓN,2023-05-25,AREA MEDICO-QUIRURGICO CUIDADOS BASICOS,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,2023-05-26,AREA MEDICO-QUIRURGICO CUIDADOS BASICOS,DOMICILIO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N39.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59.79,99.29,89.61,57.94,89.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71695588.0,NaT,2023-05-25,OBSTETRICIA Y GINECOLOGÍA,71695588,1.0,131301,"0,6406",1,1,NaN
4,106103,100390800,MUJER,2023-12-20,OTRO,SAN ANTONIO,SAN ANTONIO,CHILE,FONASA INSTITUCIONAL - (MAI) B,VALPARAISO SAN ANTONIO,SERVICIO EMERGENCIA (DOMICILIO),URGENCIA,NEONATOLOGÍA,HOSPITALIZACIÓN,2023-12-28,AREANEONATOLOGIA CUIDADOS BASICOS,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,2023-12-30,AREANEONATOLOGIA CUIDADOS BASICOS,DOMICILIO,NaN,2795.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.83,99.29,90.59,89.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,71644222,NaN,074131,"0,5346",1,1,NaN

In [15]:
parse_dates = ['FECHA_INGRESO', 'FECHATRASLADO1', 'FECHATRASLADO2', 'FECHATRASLADO3', 'FECHATRASLADO4', 'FECHATRASLADO5', 'FECHATRASLADO6', 'FECHATRASLADO7', 'FECHATRASLADO8', 'FECHATRASLADO9', 'FECHAALTA', 'FECHAPROCEDIMIENTO1', 'FECHAINTERV1']


for col in parse_dates:
    df_2023[col] = pd.to_datetime(df_2023[col], format='%d-%m-%Y', errors='coerce')

df_2023['FECHA_NACIMIENTO'] = pd.to_datetime(df_2023['FECHA_NACIMIENTO'], format='%Y-%m-%d', errors='coerce')

df_2023['FECHA_NACIMIENTO'].dropna(inplace=True)
df_2023['FECHA_INGRESO'].dropna(inplace=True)

In [16]:
limpiar_cols = ['SEXO', 'COMUNA', 'TIPO_INGRESO', 'PREVISION']

for col in limpiar_cols:
    df_2023 = df_2023[df_2023[col] != 'DESCONOCIDO']

In [17]:
df_2023['SEXO'].value_counts()

SEXO
MUJER     612169
HOMBRE    427295
Name: count, dtype: int64

In [18]:
df_2023['COMUNA'].value_counts()

COMUNA
PUENTE ALTO         39462
LA FLORIDA          23926
MAIPU               21420
VALPARAISO          20424
ARICA               19968
                    ...
TORRES DEL PAINE        5
ANTÁRTICA               3
TIMAUKEL                2
CAMARONES               2
RÍO VERDE               1
Name: count, Length: 346, dtype: int64

In [19]:
df_2023['TIPO_INGRESO'].value_counts()

TIPO_INGRESO
URGENCIA      518581
PROGRAMADA    366360
OBSTETRICA    154523
Name: count, dtype: int64

In [20]:
df_2023['PREVISION'].value_counts()

PREVISION
FONASA INSTITUCIONAL - (MAI) B    496076
FONASA INSTITUCIONAL - (MAI) A    229259
FONASA INSTITUCIONAL - (MAI) D    150693
FONASA INSTITUCIONAL - (MAI) C    130031
FONASA LIBRE ELECCIÓN (FMLE_B)      9741
ISAPRE                              6480
FONASA LIBRE ELECCIÓN (FMLE_D)      5496
PARTICULAR                          5137
FONASA LIBRE ELECCIÓN (FMLE_C)      2891
DIPRECA                             2436
CAPREDENA                            765
CAJA DE PREVISIÓN FFAA (SISA)        459
Name: count, dtype: int64

In [22]:
df_2023['ETNIA'].value_counts()

ETNIA
OTRO                       1016432
MAPUCHE                      17333
AYMARA                        2355
RAPA NUI (PASCUENSE)          1389
DIAGUITA                       837
QUECHUA                        407
YAGÁN (YÁMANA)                 247
KAWÉSQAR                       201
LICAN ANTAI (ATACAMEÑO)        182
COLLA                           81
Name: count, dtype: int64

In [23]:
del df_2023
gc.collect()

14

----

### 2022

In [ ]:
df_2022 = pd.read_csv('datos_grd/GRD_PUBLICO_2022.txt',
                      sep='|',
                      encoding='UTF-16',
                      on_bad_lines='skip',
                      low_memory=False)

,COD_HOSPITAL,CIP_ENCRIPTADO,SEXO,FECHA_NACIMIENTO,ETNIA,PROVINCIA,COMUNA,NACIONALIDAD,PREVISION,SERVICIO_SALUD,TIPO_PROCEDENCIA,TIPO_INGRESO,ESPECIALIDAD_MEDICA,TIPO_ACTIVIDAD,FECHA_INGRESO,SERVICIOINGRESO,FECHATRASLADO1,SERVICIOTRASLADO1,FECHATRASLADO2,SERVICIOTRASLADO2,FECHATRASLADO3,SERVICIOTRASLADO3,FECHATRASLADO4,SERVICIOTRASLADO4,FECHATRASLADO5,SERVICIOTRASLADO5,FECHATRASLADO6,SERVICIOTRASLADO6,FECHATRASLADO7,SERVICIOTRASLADO7,FECHATRASLADO8,SERVICIOTRASLADO8,FECHATRASLADO9,SERVICIOTRASLADO9,FECHAALTA,SERVICIOALTA,TIPOALTA,CONDICIONDEALTANEONATO1,PESORN1,SEXORN1,RN1ESTADO,CONDICIONDEALTANEONATO2,PESORN2,SEXORN2,RN2ESTADO,CONDICIONDEALTANEONATO3,PESORN3,SEXORN3,RN3ESTADO,CONDICIONDEALTANEONATO4,PESORN4,SEXORN4,RN4ESTADO,DIAGNOSTICO1,DIAGNOSTICO2,DIAGNOSTICO3,DIAGNOSTICO4,DIAGNOSTICO5,DIAGNOSTICO6,DIAGNOSTICO7,DIAGNOSTICO8,DIAGNOSTICO9,DIAGNOSTICO10,DIAGNOSTICO11,DIAGNOSTICO12,DIAGNOSTICO13,DIAGNOSTICO14,DIAGNOSTICO15,DIAGNOSTICO16,DIAGNOSTICO17,DIAGNOSTICO18,DIAGNOSTICO19,DIAGNOSTICO20,DIAGNOSTICO21,DIAGNOSTICO22,DIAGNOSTICO23,DIAGNOSTICO24,DIAGNOSTICO25,DIAGNOSTICO26,DIAGNOSTICO27,DIAGNOSTICO28,DIAGNOSTICO29,DIAGNOSTICO30,DIAGNOSTICO31,DIAGNOSTICO32,DIAGNOSTICO33,DIAGNOSTICO34,DIAGNOSTICO35,PROCEDIMIENTO1,PROCEDIMIENTO2,PROCEDIMIENTO3,PROCEDIMIENTO4,PROCEDIMIENTO5,PROCEDIMIENTO6,PROCEDIMIENTO7,PROCEDIMIENTO8,PROCEDIMIENTO9,PROCEDIMIENTO10,PROCEDIMIENTO11,PROCEDIMIENTO12,PROCEDIMIENTO13,PROCEDIMIENTO14,PROCEDIMIENTO15,PROCEDIMIENTO16,PROCEDIMIENTO17,PROCEDIMIENTO18,PROCEDIMIENTO19,PROCEDIMIENTO20,PROCEDIMIENTO21,PROCEDIMIENTO22,PROCEDIMIENTO23,PROCEDIMIENTO24,PROCEDIMIENTO25,PROCEDIMIENTO26,PROCEDIMIENTO27,PROCEDIMIENTO28,PROCEDIMIENTO29,PROCEDIMIENTO30,MEDICOINTERV1_ENCRIPTADO,FECHAPROCEDIMIENTO1,FECHAINTERV1,ESPECIALIDADINTERVENCION,MEDICOALTA_ENCRIPTADO,USOSPABELLON,IR_29301_COD_GRD,IR_29301_PESO,IR_29301_SEVERIDAD,IR_29301_MORTALIDAD,HOSPPROCEDENCIA
0,115100,98348691,HOMBRE,2022-01-02,OTRO,COLCHAGUA,SAN FERNANDO,CHILE,FONASA INSTITUCIONAL - (MAI) C,LIBERTADOR B. O HIGGINS,SERVICIO EMERGENCIA (DOMICILIO),URGENCIA,PEDIATRÍA,HOSPITALIZACIÓN,2022-08-01,CIRUGÍA INFANTIL,2022-08-05,UNIDAD DE TRATAMIENTO INTERMEDIO PEDIATRÍA,2022-08-06,PEDIATRÍA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-08-09,PEDIATRÍA,DOMICILIO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Q03.9,H55,H46,R13,N13.3,M62.89,P27.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,02.34,99.29,99.18,87.03,93.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,72370257.0,NaN,2022-08-05,NEUROCIRUGÍA,78147579,1.0,011113,"2,4156",3,1,NaN
1,112103,70532496,MUJER,1981-07-05,OTRO,COPIAPO,COPIAPO,CHILE,FONASA INSTITUCIONAL - (MAI) A,ATACAMA,OTROS HOSPITALES RED NACIONAL,PROGRAMADA,CARDIOLOGÍA,HOSPITALIZACIÓN,2022-11-01,AREA MEDICA ADULTO CUIDADOS MEDIOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-11-04,AREA MEDICA ADULTO CUIDADOS MEDIOS,DOMICILIO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I47.1,I10,E78.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.34,37.27,87.41,89.52,99.29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75385448,2.0,051401,"1,7184",1,1,HOSPITAL SAN JOSÉ DEL CARMEN (COPIAPÓ)
2,110150,68747840,MUJER,1941-06-30,OTRO,MELIPILLA,MELIPILLA,CHILE,FONASA INSTITUCIONAL - (MAI) B,METROPOLITANO OCCIDENTE,SERVICIO EMERGENCIA (DOMICILIO),URGENCIA,MEDICINA INTENSIVA ADULTO,HOSPITALIZACIÓN,2022-06-30,UNIDAD DE TRATAMIENTO INTERMEDIO (UTI) (INDIFE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-06,UNIDAD DE TRATAMIENTO INTERMEDIO (UTI) (INDIFE...,FALLECIDO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S72.00,W19.09,R57.8,I48.9,N17.9,I50.9,E11.2,I10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.44,88.26,90.59,91.39,91.32,89.59,90.39,89.66,89.54,99.29,99.19,57.94,99.17,99.04,99.07,96.39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96288218,NaN,084103,"0,9077",3,3,NaN
3,110150,98292911,MUJER,1997-01-26,OTRO,MELIPILLA,MELIPILLA,CHILE,FONASA INSTITUCIONAL - (MAI) A,METROPOLITANO OCCIDENTE,SERVICIO EMERGENCIA (DOMICILIO),OBSTETRICA,OBSTETRICIA Y GINECOLOGÍA,HOSPITALIZACIÓN,2022-07-04,OBSTETRICIA Y GINECOLOGÍA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-07,OBSTETRICIA Y GINECOLOGÍA,DOMICILIO,NaN,3350.0,HOMBRE,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,O80.0,Z37.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.59,73.6,03.91,90.39,75.34,99.29,93.96,99.24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,79334889.0,NaN,NaN,MATRONAS(ES),97016242,1.0,146131,"0,2987",1,1,NaN
4,110150,72715687,MUJER,1950-06-03,OTRO,MELIPILLA,MELIPILLA,CHILE,FONASA INSTITUCIONAL - (MAI) B,METROPOLITANO OCCIDENTE,SERVICIO EMERGENCIA (DOMICILIO),URGENCIA,MEDICINA INTENSIVA ADULTO,HOSPITALIZACIÓN,2022-06-01,UNIDAD DE TRATAMIENTO INTERMEDIO (UTI) (INDIFE...,2022-06-07,MEDICINA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-07-04,MEDICINA,DOMICILIO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J40,B96.2,U82.2,L02.3,E87.6,I10,E11.9,D64.9,F05.9,K61.0,U07.1,R41.0,G40.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86.22,91.82,87.03,99.26,38.93,99.84,89.52,99.19,99.21,90.39,93.96,99.29,89.59,89.13,93.75,91.32,91.39,99.17,99.07,57.94,93.83,87.44,96.09,86.28,99.18,99.23,96.6,93.18,93.17,89.65,83573462.0,NaN,2022-06-01,CIRUGÍA GENERAL,98947681,1.0,044213,"0,9628",3,2,NaN

In [ ]:
df_2022.head()

In [ ]:
parse_dates = ['FECHA_NACIMIENTO', 'FECHA_INGRESO', 'FECHATRASLADO1', 'FECHATRASLADO2', 'FECHATRASLADO3', 'FECHATRASLADO4', 'FECHATRASLADO5', 'FECHATRASLADO6', 'FECHATRASLADO7', 'FECHATRASLADO8', 'FECHATRASLADO9', 'FECHAALTA', 'FECHAPROCEDIMIENTO1', 'FECHAINTERV1']

for col in parse_dates:
    df_2022[col] = pd.to_datetime(df_2022[col], format='%Y-%m-%d', errors='coerce')

df_2022['FECHA_NACIMIENTO'].dropna(inplace=True)
df_2022['FECHA_INGRESO'].dropna(inplace=True)

In [ ]:
limpiar_cols = ['SEXO', 'COMUNA', 'TIPO_INGRESO', 'PREVISION', 'PROVINCIA']

for col in limpiar_cols:
    df_2022 = df_2022[df_2022[col] != 'DESCONOCIDO']

In [ ]:
del df_2022
gc.collect()

----

### 2021

In [6]:
df_2021 = pd.read_csv('datos_grd/GRD_PUBLICO_2021.txt',
                      sep='|',
                      encoding='UTF-8',
                      on_bad_lines='skip',
                      low_memory=False)

In [19]:
df_2021

,COD_HOSPITAL,CIP_ENCRIPTADO,SEXO,FECHA_NACIMIENTO,ETNIA,PROVINCIA,COMUNA,NACIONALIDAD,PREVISION,SERVICIO_SALUD,TIPO_PROCEDENCIA,TIPO_INGRESO,ESPECIALIDAD_MEDICA,TIPO_ACTIVIDAD,FECHA_INGRESO,SERVICIOINGRESO,FECHATRASLADO1,SERVICIOTRASLADO1,FECHATRASLADO2,SERVICIOTRASLADO2,FECHATRASLADO3,SERVICIOTRASLADO3,FECHATRASLADO4,SERVICIOTRASLADO4,FECHATRASLADO5,SERVICIOTRASLADO5,FECHATRASLADO6,SERVICIOTRASLADO6,FECHATRASLADO7,SERVICIOTRASLADO7,FECHATRASLADO8,SERVICIOTRASLADO8,FECHATRASLADO9,SERVICIOTRASLADO9,FECHAALTA,SERVICIOALTA,TIPOALTA,CONDICIONDEALTANEONATO1,PESORN1,SEXORN1,RN1ESTADO,CONDICIONDEALTANEONATO2,PESORN2,SEXORN2,RN2ESTADO,CONDICIONDEALTANEONATO3,PESORN3,SEXORN3,RN3ESTADO,CONDICIONDEALTANEONATO4,PESORN4,SEXORN4,RN4ESTADO,DIAGNOSTICO1,DIAGNOSTICO2,DIAGNOSTICO3,DIAGNOSTICO4,DIAGNOSTICO5,DIAGNOSTICO6,DIAGNOSTICO7,DIAGNOSTICO8,DIAGNOSTICO9,DIAGNOSTICO10,DIAGNOSTICO11,DIAGNOSTICO12,DIAGNOSTICO13,DIAGNOSTICO14,DIAGNOSTICO15,DIAGNOSTICO16,DIAGNOSTICO17,DIAGNOSTICO18,DIAGNOSTICO19,DIAGNOSTICO20,DIAGNOSTICO21,DIAGNOSTICO22,DIAGNOSTICO23,DIAGNOSTICO24,DIAGNOSTICO25,DIAGNOSTICO26,DIAGNOSTICO27,DIAGNOSTICO28,DIAGNOSTICO29,DIAGNOSTICO30,DIAGNOSTICO31,DIAGNOSTICO32,DIAGNOSTICO33,DIAGNOSTICO34,DIAGNOSTICO35,PROCEDIMIENTO1,PROCEDIMIENTO2,PROCEDIMIENTO3,PROCEDIMIENTO4,PROCEDIMIENTO5,PROCEDIMIENTO6,PROCEDIMIENTO7,PROCEDIMIENTO8,PROCEDIMIENTO9,PROCEDIMIENTO10,PROCEDIMIENTO11,PROCEDIMIENTO12,PROCEDIMIENTO13,PROCEDIMIENTO14,PROCEDIMIENTO15,PROCEDIMIENTO16,PROCEDIMIENTO17,PROCEDIMIENTO18,PROCEDIMIENTO19,PROCEDIMIENTO20,PROCEDIMIENTO21,PROCEDIMIENTO22,PROCEDIMIENTO23,PROCEDIMIENTO24,PROCEDIMIENTO25,PROCEDIMIENTO26,PROCEDIMIENTO27,PROCEDIMIENTO28,PROCEDIMIENTO29,PROCEDIMIENTO30,MEDICOINTERV1_ENCRIPTADO,FECHAPROCEDIMIENTO1,FECHAINTERV1,ESPECIALIDADINTERVENCION,MEDICOALTA_ENCRIPTADO,USOSPABELLON,IR_29301_COD_GRD,IR_29301_PESO,IR_29301_SEVERIDAD,IR_29301_MORTALIDAD,HOSPPROCEDENCIA
0,116100,74638412.0,HOMBRE,1973-09-16,NINGUNO,CURICO,MOLINA,CHILE,FONASA INSTITUCIONAL - (MAI) A,DEL MAULE,DESCONOCIDO,PROGRAMADA,TRAUMATOLOGÍA Y ORTOPEDIA,CIRUGÍA MAYOR AMBULATORIA (CMA),2021-11-17,UNIDAD DE RECUPERACIÓN DE PABELLONES (CENTRAL ...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,2021-11-17,UNIDAD DE RECUPERACIÓN DE PABELLONES (CENTRAL ...,DOMICILIO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,G56.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04.43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87942922.0,NaT,2021-11-17,TRAUMATOLOGÍA Y ORTOPEDIA,87942922,2.0,12130,",3045",0,0,NaN
1,116100,68302016.0,MUJER,1956-10-20,NINGUNO,CURICO,CURICO,CHILE,FONASA INSTITUCIONAL - (MAI) B,DEL MAULE,DESCONOCIDO,PROGRAMADA,TRAUMATOLOGÍA Y ORTOPEDIA,CIRUGÍA MAYOR AMBULATORIA (CMA),2021-11-17,UNIDAD DE RECUPERACIÓN DE PABELLONES (CENTRAL ...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,2021-11-17,UNIDAD DE RECUPERACIÓN DE PABELLONES (CENTRAL ...,DOMICILIO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,G56.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04.43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87942922.0,NaT,2021-11-17,TRAUMATOLOGÍA Y ORTOPEDIA,87942922,2.0,12130,",3045",0,0,NaN
2,113150,74812628.0,MUJER,1983-01-06,NINGUNO,MAIPO,PAINE,CHILE,FONASA INSTITUCIONAL - (MAI) B,METROPOLITANO SUR,SERVICIO EMERGENCIA (DOMICILIO),URGENCIA,MEDICINA INTERNA,HOSPITALIZACIÓN,2021-10-19,MEDICINA,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,2021-10-27,MEDICINA,DOMICILIO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,J18.9,N10,K42.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.41,88.01,87.44,90.39,93.94,90.59,91.33,91.39,99.21,99.29,89.39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,98028196,NaN,44162,",6172",2,1,NaN
3,110150,71155961.0,MUJER,1964-10-08,NINGUNO,MELIPILLA,SAN PEDRO,CHILE,FONASA INSTITUCIONAL - (MAI) A,METROPOLITANO OCCIDENTE,"CENTRO ESPECIALIDADES (CDT, CRS, CONSULTORIO A...",OBSTETRICA,OBSTETRICIA Y GINECOLOGÍA,HOSPITALIZACIÓN,2021-03-12,OBSTETRICIA Y GINECOLOGÍA,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,2021-03-12,OBSTETRICIA Y GINECOLOGÍA,DOMICILIO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N92.5,N85.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,69.09,99.29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70174961.0,NaT,2021-03-12,OBSTETRICIA Y GINECOLOGÍA,70174961,1.0,131111,",5227",1,1,NaN
4,114101,77660869.0,MUJER,2012-08-24,NINGUNO,CORDILLERA,PUENTE ALTO,CHILE,FONASA INSTITUCIONAL - (MAI) A,METROPOLITANO SURORIENTE,SERVICIO EMERGENCIA (DOMICILIO),URGENCIA,PEDIATRÍA,HOSPITALIZACIÓN,2021-04-12,PEDIATRÍA,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,2021-04-12,PEDIATRÍA,DOMICILIO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,K59.0,B97.1,J45.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88.76,88.78,91.39,90.59,99.26,99.29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,69379749,NaN,64181,",4872",1,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
816904,105100,68882797.0,HOMBRE,1942-06-25,NINGUNO,ELQUI,VICUÑA,CHILE,FONASA INSTITUCIONAL - (MAI) B,COQUIMBO,OTROS HOSPITALES DE LA RED,URGENCIA,MEDICINA INTERNA,HOSPITALIZACIÓN,2021-11-04,UNIDAD DE TRATAMIENTO INTERMEDIO (UTI) (INDIFE...,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,2021-11-12,UNIDAD DE TRATAMIENTO INTERMEDIO (UTI) (INDIFE...,DOMICILIO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N39.0,B96.1,N17.9,T83.0,Y84.6,J44.9,F17.1,N41.9,L27.1,Y51.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.17,00.17,93.18,93.83,91.33,99.21,99.29,99.18,38.91,89.54,89.38,96.59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,96596244,NaN,111403,"1,6547",3,3,HOSPITAL SAN JUAN DE DIOS (VICUÑA)
816905,120101,97789022.0,HOMBRE,2020-12-30,NINGUNO,BIO-BIO,LOS ÁNGELES,CHILE,FONASA INSTITUCIONAL - (MAI) B,BIOBIO,"CENTRO ESPECIALIDADES (CDT, CRS, CONSULTORIO A...",PROGRAMADA,CIRUGÍA PEDIÁTRICA,HOSPITALIZACIÓN,2021-02-24,CIRUGÍA INFANTIL,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,2021-02-26,CIRUGÍA INFANTIL,DOMICILIO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,K40.9,K42.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,53.00,53.49,96.59,99.29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,72218771.0,NaT,2021-02-25,CIRUGÍA PEDIÁTRICA,68862253,1.0,61121,",8122",1,1,NaN
816906,114101,71164179.0,MUJER,1947-05-11,NINGUNO,CORDILLERA,PUENTE ALTO,CHILE,FONASA INSTITUCIONAL - (MAI) B,METROPOLITANO SURORIENTE,"CENTRO ESPECIALIDADES (CDT, CRS, CONSULTORIO A...",PROGRAMADA,ONCOLOGÍA MÉDICA,HOSPITALIZACIÓN,2021-11-16,ONCOLOGÍA,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,2021-11-16,ONCOLOGÍA,DOMICILIO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Z51.8,C91.1,C44.3,I70.00,I10,E11.9,E03.9,Z92.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00.18,99.23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,87934066,NaN,224122,"1,0867",2,2,NaN
816907,107100,78884679.0,HOMBRE,1958-07-24,NINGUNO,VALPARAISO,VIÑA DEL MAR,CHILE,FONASA INSTITUCIONAL - (MAI) D,VIÑA DEL MAR QUILLOTA,CONSULTA PRIVADA,URGENCIA,CIRUGÍA DIGESTIVA,HOSPITALIZACIÓN,2021-08-01,CIRUGÍA,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,2021-08-03,CIRUGÍA,DOMICILIO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,K80.0,I10,I25.2,Z88.0,Z95.5,Z92.4,F17.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,68804909.0,NaT,2021-08-02,CIRUGÍA DIGESTIVA,68804909,1.0,71142,"1,1472",2,2,NaN
816908,102100,71716269.0,MUJER,1973-04-13,NINGUNO,IQUIQUE,IQUIQUE,CHILE,FONASA INSTITUCIONAL - (MAI) B,IQUIQUE,SERVICIO EMERGENCIA (DOMICILIO),URGENCIA,MEDICINA INTERNA,HOSPITALIZACIÓN,2021-06-11,MEDICINA,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,NaT,NaN,2021-06-17,MEDICINA,ALTA VOLUNTARIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N10,Z03.8,K80.2,N83.2,E11.6,Z86.1,Z87.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.71,88.76,99.21,99.17,99.19,89.65,89.66,90.49,99.29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,74887734,NaN,114122,",5701",2,2,NaN

In [ ]:
parse_dates = ['FECHA_NACIMIENTO', 'FECHA_INGRESO', 'FECHATRASLADO1', 'FECHATRASLADO2', 'FECHATRASLADO3', 'FECHATRASLADO4', 'FECHATRASLADO5', 'FECHATRASLADO6', 'FECHATRASLADO7', 'FECHATRASLADO8', 'FECHATRASLADO9', 'FECHAALTA', 'FECHAPROCEDIMIENTO1', 'FECHAINTERV1']

for col in parse_dates:
    df_2021[col] = pd.to_datetime(df_2021[col], format='%Y-%m-%d', errors='coerce')

df_2021['FECHA_NACIMIENTO'].dropna(inplace=True)
df_2021['FECHA_INGRESO'].dropna(inplace=True)

In [20]:
limpiar_cols = ['SEXO', 'COMUNA', 'TIPO_INGRESO', 'PREVISION', 'PROVINCIA']

for col in limpiar_cols:
    df_2021 = df_2021[df_2021[col] != 'DESCONOCIDO']

In [ ]:
del df_2021
gc.collect()

-----

### 2020

In [ ]:
df_2021 = pd.read_csv('datos_grd/GRD_PUBLICO_2021.txt',
                      sep='|',
                      encoding='UTF-8',
                      on_bad_lines='skip',
                      low_memory=False)

-----

### 2019